(() => {
'use strict';
const $ = s => document.querySelector(s);
const exprEl=$('#expression'), resultEl=$('#result'), previewEl=$('#preview'), historyEl=$('#history'), toastEl=$('#toast');
let expression='', answer=0, memory=0, justEvaluated=false, history=JSON.parse(sessionStorage.getItem('numvero-history')||'[]'), undoStack=[], redoStack=[];
const save=()=>sessionStorage.setItem('numvero-history',JSON.stringify(history));
const snapshot=()=>{undoStack.push({expression,answer,justEvaluated});if(undoStack.length>80)undoStack.shift();redoStack=[]};
const restore=s=>{expression=s.expression;answer=s.answer;justEvaluated=s.justEvaluated;render()};
function clean(n){if(!Number.isFinite(n)) throw new Error(n===0?'Invalid result':'Result is too large'); if(Object.is(n,-0))return 0; return Number.parseFloat(n.toPrecision(14));}
function format(n){if(typeof n!=='number'||!Number.isFinite(n))return 'Error';if(Math.abs(n)>=1e15|| (Math.abs(n)>0&&Math.abs(n)<1e-9)) return n.toExponential(8).replace(/\.0+e/,'e').replace(/(\.\d*?[1-9])0+e/,'$1e');let s=String(clean(n));if(s.includes('e'))return s;let [a,b]=s.split('.');let sign='';if(a.startsWith('-')){sign='-';a=a.slice(1)}a=a.replace(/\B(?=(\d{3})+(?!\d))/g,',');return sign+a+(b?'.'+b:'');}
function displayExpr(s){return s.replace(/\*/g,'×').replace(/\//g,'÷').replace(/-/g,'−');}
function tokenize(s){let t=[],i=0;while(i<s.length){let c=s[i];if(/\s/.test(c)){i++;continue}if(/[0-9.]/.test(c)){let j=i,dots=0;while(j<s.length&&/[0-9.eE+-]/.test(s[j])){if(s[j]==='.')dots++;if((s[j]==='+'||s[j]==='-')&&j>i&&!/[eE]/.test(s[j-1]))break;if(/[eE]/.test(s[j])&&j+1<s.length&&/[+-]/.test(s[j+1]))j++;j++;}let raw=s.slice(i,j);if(dots>1||!/^((\d+(\.\d*)?)|(\.\d+))([eE][+-]?\d+)?$/.test(raw))throw new Error('Invalid number');t.push({type:'num',value:Number(raw)});i=j;continue}if('+-*/()%'.includes(c)){t.push({type:'op',value:c});i++;continue}throw new Error('Invalid character')}return t;}
function evaluate(s){let tokens=tokenize(s), output=[], ops=[], prev=null;for(const tok of tokens){if(tok.type==='num'){output.push(tok);prev='num';continue}let op=tok.value;if(op==='%' ){if(prev!=='num'&&prev!==')')throw new Error('Invalid percent');output.push({type:'postfix',value:'%'});prev='%';continue}if(op==='('){if(prev==='num'||prev===')')throw new Error('Missing operator');ops.push(op);prev='(';continue}if(op===')'){if(prev===null||prev==='op'||prev==='(')throw new Error('Invalid parentheses');while(ops.length&&ops.at(-1)!=='(')output.push({type:'op',value:ops.pop()});if(ops.pop()!=='(')throw new Error('Invalid parentheses');prev=')';continue}if(prev===null||prev==='('||prev==='op'){if(op==='-'||op==='+'){op=op==='-'?'u-':'u+'}else throw new Error('Missing number')}const prec={'u-':4,'u+':4,'*':3,'/':3,'+':2,'-':2};const right=op==='u-'||op==='u+';while(ops.length&&ops.at(-1)!=='('&&((right?prec[op]<prec[ops.at(-1)]:prec[op]<=prec[ops.at(-1)])))output.push({type:'op',value:ops.pop()});ops.push(op);prev='op'}if(prev==='op'||prev==='('||prev===null)throw new Error('Incomplete expression');while(ops.length){if(ops.at(-1)==='(')throw new Error('Unclosed parenthesis');output.push({type:'op',value:ops.pop()})}let stack=[];for(const tok of output){if(tok.type==='num')stack.push(tok.value);else if(tok.type==='postfix'){let a=stack.pop();if(a===undefined)throw new Error('Invalid percent');stack.push(a/100)}else{let op=tok.value;if(op==='u-'||op==='u+'){let a=stack.pop();if(a===undefined)throw new Error('Invalid sign');stack.push(op==='u-'?-a:a);continue}let b=stack.pop(),a=stack.pop();if(a===undefined||b===undefined)throw new Error('Invalid expression');if(op==='/'&&b===0)throw new Error('Cannot divide by zero');let v=op==='+'?a+b:op==='-'?a-b:op==='*'?a*b:a/b;if(!Number.isFinite(v))throw new Error('Number is too large');stack.push(v)}}if(stack.length!==1)throw new Error('Invalid expression');return clean(stack[0]);}
function render(){exprEl.textContent=expression?displayExpr(expression):'0';let val;if(!expression){val=0;previewEl.textContent=''}else{try{val=evaluate(expression);previewEl.textContent='≈ '+format(val)}catch(e){val=answer;previewEl.textContent=e.message}}resultEl.textContent=format(val??0);document.title=expression?`${displayExpr(expression)} = ${format(val)} · Numvero`:'Numvero — Fast Online Calculator';}
function toast(msg){toastEl.textContent=msg;toastEl.classList.add('show');clearTimeout(toast.timer);toast.timer=setTimeout(()=>toastEl.classList.remove('show'),1300)}
function commit(){snapshot();}
function append(v){if(justEvaluated&&!/[+*/%)]/.test(v)){expression='';}if(v==='.'&&(/(?:^|[+\-*/(])\d*\.?\d*$/.test(expression)&&expression.match(/(?:^|[+\-*/(])([0-9.]+)$/)?.[1]?.includes('.')))return;if(v==='('&&expression&&/[0-9)]$/.test(expression))expression+='*';if(v===')'&&(!expression||/[+\-*/(]$/.test(expression)))return;if('%'===v&&(!expression||/[+\-*/(.]$/.test(expression)))return;expression+=v;justEvaluated=false;render()}
function clear(){commit();expression='';answer=0;justEvaluated=false;render()}
function clearEntry(){commit();expression=expression.slice(0,-1);render()}
function sign(){commit();let m=expression.match(/(\d+(?:\.\d+)?(?:e[+-]?\d+)?)$/i);if(!m)return;if(m.index===0)expression='-'+expression;else{let i=m.index;let before=expression[i-1];if(before==='-'){expression=expression.slice(0,i-1)+expression.slice(i)}else expression=expression.slice(0,i)+'-'+expression.slice(i)}render()}
function equals(){if(!expression)return;try{let value=evaluate(expression);answer=value;history.unshift({id:crypto.randomUUID?crypto.randomUUID():String(Date.now()),expression,result:value});history=history.slice(0,60);save();justEvaluated=true;render();toast('Calculated')}catch(e){resultEl.textContent='Error';previewEl.textContent=e.message;toast(e.message)}}
function reuse(item){commit();expression=String(item.result);answer=item.result;justEvaluated=false;render()}
function renderHistory(){historyEl.innerHTML='';if(!history.length){historyEl.innerHTML='<p class="empty-history">Your recent calculations will appear here.</p>';return}for(const item of history){let row=document.createElement('div');row.className='history-item';let use=document.createElement('button');use.className='history-use';use.type='button';use.innerHTML=`<span class="history-expr">${escapeHtml(displayExpr(item.expression))}</span><span class="history-result">= ${escapeHtml(format(item.result))}</span>`;use.addEventListener('click',()=>reuse(item));let del=document.createElement('button');del.className='history-delete';del.type='button';del.setAttribute('aria-label','Delete calculation');del.textContent='×';del.addEventListener('click',()=>{history=history.filter(x=>x.id!==item.id);save();renderHistory()});row.append(use,del);historyEl.append(row)}}
function escapeHtml(s){return s.replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function currentValue(){try{return evaluate(expression||'0')}catch{return answer}}
function memory(action){let v=currentValue();if(action==='MC')memory=0;if(action==='MR'){commit();expression=String(memory);justEvaluated=false;render()}if(action==='Mplus')memory=clean(memory+v);if(action==='Mminus')memory=clean(memory-v);if(action!=='MR')toast(action==='MC'?'Memory cleared':'Memory updated')}
async function copy(text,label){try{await navigator.clipboard.writeText(text);toast(label+' copied')}catch{toast('Copy unavailable')}}
function share(){let url=new URL(location.href);url.hash=expression?'calc='+btoa(unescape(encodeURIComponent(expression))):'';copy(url.href,'Share link')}
function undo(){let s=undoStack.pop();if(!s)return;redoStack.push({expression,answer,justEvaluated});restore(s)}
function redo(){let s=redoStack.pop();if(!s)return;undoStack.push({expression,answer,justEvaluated});restore(s)}
document.querySelectorAll('[data-value]').forEach(b=>b.addEventListener('click',()=>append(b.dataset.value)));
document.querySelector('[data-action="clear"]').addEventListener('click',clear);document.querySelector('[data-action="clear-entry"]').addEventListener('click',clearEntry);document.querySelector('[data-action="backspace"]').addEventListener('click',clearEntry);document.querySelector('[data-action="sign"]').addEventListener('click',sign);document.querySelector('[data-action="equals"]').addEventListener('click',equals);
document.querySelectorAll('[data-memory]').forEach(b=>b.addEventListener('click',()=>memory(b.dataset.memory)));
$('#clearHistory').addEventListener('click',()=>{history=[];save();renderHistory();toast('History cleared')});$('#copyResult').addEventListener('click',()=>copy(format(currentValue()),'Result'));$('#copyCalc').addEventListener('click',()=>copy(`${displayExpr(expression)} = ${format(currentValue())}`,'Calculation'));$('#shareBtn').addEventListener('click',share);
$('#themeBtn').addEventListener('click',()=>{document.body.classList.toggle('dark');localStorage.setItem('numvero-theme',document.body.classList.contains('dark')?'dark':'light');$('#themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾'});
window.addEventListener('keydown',e=>{if(e.ctrlKey&&e.key.toLowerCase()==='z'){e.preventDefault();undo();return}if(e.ctrlKey&&e.key.toLowerCase()==='y'){e.preventDefault();redo();return}if(e.key==='Enter'||e.key==='='){e.preventDefault();equals();return}if(e.key==='Escape'){e.preventDefault();clear();return}if(e.key==='Backspace'){e.preventDefault();clearEntry();return}let map={'+':'+','-':'-','*':'*','/':'/','%':'%','(':'(',')':')','.':'.'};if(/[0-9]/.test(e.key))append(e.key);else if(map[e.key]){e.preventDefault();append(map[e.key])}});
(function init(){if(localStorage.getItem('numvero-theme')==='dark'||(!localStorage.getItem('numvero-theme')&&matchMedia('(prefers-color-scheme: dark)').matches)){document.body.classList.add('dark');$('#themeBtn').textContent='☀'}let h=location.hash.match(/^#calc=(.+)$/);if(h){try{expression=decodeURIComponent(escape(atob(h[1])))}catch{expression=''}}render();renderHistory()})();
})();