const tools=[
{id:'basic',name:'Basic Calculator',icon:'+',desc:'Everyday arithmetic with brackets, percentages and keyboard input.',keywords:'math arithmetic add subtract multiply divide'},
{id:'scientific',name:'Scientific Calculator',icon:'√',desc:'Trigonometry, logarithms, powers, roots, constants and DEG/RAD modes.',keywords:'science sin cos tan log ln sqrt power'},
{id:'percentage',name:'Percentage Calculator',icon:'%',desc:'Find a percentage, percentage change, increase, decrease, discount and tip.',keywords:'percent discount increase decrease tip change'},
{id:'age',name:'Age Calculator',icon:'AGE',desc:'Calculate an exact age in years, months and days from two dates.',keywords:'age birthday date dob days'},
{id:'simple',name:'Simple Interest Calculator',icon:'SI',desc:'Calculate simple interest and total amount from principal, rate and time.',keywords:'simple interest finance money'},
{id:'compound',name:'Compound Interest Calculator',icon:'CI',desc:'Estimate compound growth with flexible compounding periods.',keywords:'compound interest investment growth finance'},
{id:'emi',name:'Loan EMI Calculator',icon:'₹',desc:'Estimate monthly EMI, total repayment and total interest on a loan.',keywords:'emi loan finance monthly payment'},
{id:'ratio',name:'Ratio Calculator',icon:'∶',desc:'Simplify ratios and split a total proportionally.',keywords:'ratio proportion simplify split'},
{id:'units',name:'Unit Converter',icon:'↔',desc:'Convert length, weight and temperature instantly.',keywords:'units conversion length weight temperature'}
];
const $=s=>document.querySelector(s), $$=s=>document.querySelectorAll(s);
const fmt=n=>Number.isFinite(n)?Number(n.toFixed(10)).toLocaleString('en-IN',{maximumFractionDigits:10}):'Error';
const val=k=>{const x=document.querySelector(`[name="${k}"]`);return x?Number(x.value):NaN};
function renderCards(filter=''){const q=filter.trim().toLowerCase();const list=tools.filter(t=>(t.name+' '+t.desc+' '+t.keywords).toLowerCase().includes(q));$('#cards').innerHTML=list.map((t,i)=>`<button class="tool-card" data-tool="${t.id}"><div class="tool-number">${String(i+1).padStart(2,'0')}</div><div class="tool-icon">${t.icon}</div><h3>${t.name}</h3><p>${t.desc}</p><span class="tool-link">Open calculator →</span></button>`).join('');$('#noResults').hidden=list.length>0;$$('[data-tool]').forEach(b=>b.onclick=()=>openTool(b.dataset.tool));}
function input(label,name,type='number',placeholder=''){return `<label class="field"><span>${label}</span><input name="${name}" type="${type}" placeholder="${placeholder}" ${type==='number'?'step="any"':''}></label>`}
function select(label,name,options){return `<label class="field"><span>${label}</span><select name="${name}">${options.map(x=>`<option>${x}</option>`).join('')}</select></label>`}
let active='';
function openTool(id){active=id;const t=tools.find(x=>x.id===id);$('#modalTitle').textContent=t.name;$('#result').textContent='Enter values and calculate.';let h='';
if(id==='basic'||id==='scientific'){h=`<input id="expr" class="calc-display" inputmode="decimal" autocomplete="off" placeholder="0" aria-label="Expression"><div class="science">${id==='scientific'?['sin(','cos(','tan(','sqrt(','log(','ln(','π','e','^'].map(x=>`<button type="button" data-insert="${x}">${x}</button>`).join(''):''}</div><div class="keypad">${['C','⌫','(',')','7','8','9','÷','4','5','6','×','1','2','3','−','0','.','%','+','='].map(x=>`<button type="button" data-key="${x}" class="${x==='='?'primary-key':''}">${x}</button>`).join('')}</div>${id==='scientific'?'<div class="switch">Angle mode <button id="angleMode" type="button">DEG</button></div>':''}`;
}else if(id==='percentage'){h=`<div class="form-grid">${input('Percentage','p')} ${input('Number','n')} ${input('Original value','old')} ${input('New value','new')}</div><p class="hint">Fill Percentage + Number for a direct percentage. Or Original + New for percentage change.</p>`;
}else if(id==='age'){h=`<div class="form-grid">${input('Date of birth','dob','date')} ${input('Calculate on','asof','date')}</div>`;
}else if(id==='simple'){h=`<div class="form-grid">${input('Principal','p')} ${input('Annual rate (%)','r')} ${input('Time (years)','t')}</div>`;
}else if(id==='compound'){h=`<div class="form-grid">${input('Principal','p')} ${input('Annual rate (%)','r')} ${input('Time (years)','t')} ${input('Compounds per year','n')}</div>`;
}else if(id==='emi'){h=`<div class="form-grid">${input('Loan amount','p')} ${input('Annual interest (%)','r')} ${input('Loan term (years)','t')}</div><p class="hint">This is an estimate; actual lender terms can differ.</p>`;
}else if(id==='ratio'){h=`<div class="form-grid">${input('First value','a')} ${input('Second value','b')} ${input('Total to split (optional)','total')}</div>`;
}else if(id==='units'){h=`<div class="form-grid">${select('Category','cat',['Length','Weight','Temperature'])}${input('Value','value')}${select('From','from',['Meters','Kilometers','Centimeters','Millimeters','Miles','Feet','Inches'])}${select('To','to',['Meters','Kilometers','Centimeters','Millimeters','Miles','Feet','Inches'])}</div>`;}
$('#toolBody').innerHTML=h+(id==='basic'||id==='scientific'?'':'<button id="calculate" class="calculate-button" type="button">Calculate →</button>');$('#modal').hidden=false;document.body.style.overflow='hidden';wireTool();}
function closeTool(){$('#modal').hidden=true;document.body.style.overflow='';active='';}
function wireTool(){
$$('[data-close]').forEach(x=>x.onclick=closeTool);$$('[data-insert]').forEach(b=>b.onclick=()=>{$('#expr').value+={"π":"pi","e":"e"}[b.dataset.insert]||b.dataset.insert;$('#expr').focus()});
$$('[data-key]').forEach(b=>b.onclick=()=>keyPress(b.dataset.key));if($('#calculate'))$('#calculate').onclick=calculate;if($('#angleMode'))$('#angleMode').onclick=()=>$('#angleMode').textContent=$('#angleMode').textContent==='DEG'?'RAD':'DEG';
const ex=$('#expr');if(ex){ex.focus();ex.onkeydown=e=>{if(e.key==='Enter')calculate();if(e.key==='Escape')closeTool()};}
const cat=document.querySelector('[name="cat"]');if(cat)cat.onchange=()=>{const temp=cat.value==='Temperature';const from=document.querySelector('[name="from"]'),to=document.querySelector('[name="to"]');const opts=temp?['Celsius','Fahrenheit','Kelvin']:cat.value==='Weight'?['Kilograms','Grams','Milligrams','Pounds','Ounces']:['Meters','Kilometers','Centimeters','Millimeters','Miles','Feet','Inches'];[from,to].forEach(s=>s.innerHTML=opts.map(x=>`<option>${x}</option>`).join(''));};
}
function keyPress(k){const e=$('#expr');if(k==='=')return calculate();if(k==='C')e.value='';else if(k==='⌫')e.value=e.value.slice(0,-1);else e.value+=k;e.focus();}
function evalMath(s,deg=true){s=s.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('%','/100').replaceAll('√','sqrt').replaceAll('π','pi').replace(/\s+/g,'');if(!/^[0-9+\-*/%^().,a-z]+$/i.test(s))throw Error();const tokens=s.match(/asin|acos|atan|sin|cos|tan|sqrt|log|ln|pi|e|\d*\.?\d+|[+\-*/%^()]/g)||[];let i=0;const primary=()=>{const t=tokens[i++];if(t==null)throw Error();if(/^\d|^\.\d/.test(t))return +t;if(t==='pi')return Math.PI;if(t==='e')return Math.E;if(t==='+')return primary();if(t==='-')return -primary();if(t==='('){const x=expr();if(tokens[i++]!==')')throw Error();return x}if(['sin','cos','tan','asin','acos','atan','sqrt','log','ln'].includes(t)){if(tokens[i++]!=='(')throw Error();const x=expr();if(tokens[i++]!==')')throw Error();const r=deg?x*Math.PI/180:x,inv=deg?180/Math.PI:1;return t==='sin'?Math.sin(r):t==='cos'?Math.cos(r):t==='tan'?Math.tan(r):t==='asin'?Math.asin(x)*inv:t==='acos'?Math.acos(x)*inv:t==='atan'?Math.atan(x)*inv:t==='sqrt'?Math.sqrt(x):t==='log'?Math.log10(x):Math.log(x)}throw Error()};const power=()=>{let a=primary();if(tokens[i]==='^'){i++;a=Math.pow(a,power())}return a};const term=()=>{let a=power();while(tokens[i]==='*'||tokens[i]==='/'){const o=tokens[i++],b=power();a=o==='*'?a*b:a/b}return a};const expr=()=>{let a=term();while(tokens[i]==='+'||tokens[i]==='-'){const o=tokens[i++],b=term();a=o==='+'?a+b:a-b}return a};const out=expr();if(i!==tokens.length||!Number.isFinite(out))throw Error();return out;}
function calculate(){try{let text='';if(active==='basic'||active==='scientific'){const mode=$('#angleMode')?.textContent!=='RAD';text=fmt(evalMath($('#expr').value,mode));}else if(active==='percentage'){const p=val('p'),n=val('n'),o=val('old'),ne=val('new');if(Number.isFinite(p)&&Number.isFinite(n))text=`${fmt(p)}% of ${fmt(n)} = ${fmt(p*n/100)}`;else if(Number.isFinite(o)&&Number.isFinite(ne)&&o!==0)text=`Percentage change: ${fmt((ne-o)/Math.abs(o)*100)}%`;else throw Error();}else if(active==='age'){const d=new Date($('[name="dob"]').value+'T00:00:00'),e=new Date(($('[name="asof"]').value||new Date().toISOString().slice(0,10))+'T00:00:00');if(!Number.isFinite(d.getTime())||d>e)throw Error();let y=e.getFullYear()-d.getFullYear(),m=e.getMonth()-d.getMonth(),day=e.getDate()-d.getDate();if(day<0){m--;day+=new Date(e.getFullYear(),e.getMonth(),0).getDate()}if(m<0){y--;m+=12}text=`Exact age: ${y} years, ${m} months, ${day} days`;}else if(active==='simple'){const p=val('p'),r=val('r'),t=val('t');if([p,r,t].some(x=>!Number.isFinite(x)))throw Error();const i=p*r*t/100;text=`Simple interest: ${fmt(i)}\nTotal amount: ${fmt(p+i)}`;}else if(active==='compound'){const p=val('p'),r=val('r'),t=val('t'),n=val('n');if([p,r,t,n].some(x=>!Number.isFinite(x))||n<=0)throw Error();const a=p*Math.pow(1+r/100/n,n*t);text=`Compound interest: ${fmt(a-p)}\nFinal amount: ${fmt(a)}`;}else if(active==='emi'){const p=val('p'),r=val('r'),t=val('t');if([p,r,t].some(x=>!Number.isFinite(x))||t<=0)throw Error();const n=t*12,rm=r/1200,e=rm===0?p/n:p*rm*Math.pow(1+rm,n)/(Math.pow(1+rm,n)-1);text=`Monthly EMI: ${fmt(e)}\nTotal payment: ${fmt(e*n)}\nTotal interest: ${fmt(e*n-p)}`;}else if(active==='ratio'){const a=val('a'),b=val('b'),total=val('total');if(!Number.isFinite(a)||!Number.isFinite(b)||a<=0||b<=0)throw Error();const gcd=(x,y)=>y?gcd(y,x%y):Math.abs(x),g=gcd(a,b);text=`Simplified ratio: ${a/g} : ${b/g}`;if(Number.isFinite(total))text+=`\nSplit: ${fmt(total*a/(a+b))} and ${fmt(total*b/(a+b))}`;}else if(active==='units'){const x=val('value'),from=$('[name="from"]').value,to=$('[name="to"]').value;if(!Number.isFinite(x))throw Error();text=`${fmt(convert(x,from,to))} ${to}`;}$('#result').textContent=text;}catch{$('#result').textContent='Please enter valid values.'}}
function convert(x,f,t){if(f===t)return x;const length={Meters:1,Kilometers:1000,Centimeters:.01,Millimeters:.001,Miles:1609.344,Feet:.3048,Inches:.0254},weight={Kilograms:1,Grams:.001,Milligrams:.000001,Pounds:.45359237,Ounces:.028349523125};if(length[f]&&length[t])return x*length[f]/length[t];if(weight[f]&&weight[t])return x*weight[f]/weight[t];if(['Celsius','Fahrenheit','Kelvin'].includes(f)){let c=f==='Celsius'?x:f==='Fahrenheit'?(x-32)*5/9:x-273.15;return t==='Celsius'?c:t==='Fahrenheit'?c*9/5+32:c+273.15}throw Error();}
$('#search').oninput=e=>renderCards(e.target.value);$('#clearSearch').onclick=()=>{$('#search').value='';renderCards()};$('#randomBtn').onclick=()=>openTool(tools[Math.floor(Math.random()*tools.length)].id);$$('[data-close]').forEach(x=>x.onclick=closeTool);document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!$('#modal').hidden)closeTool()});
const saved=localStorage.getItem('numvero-theme');if(saved==='dark')document.body.classList.add('dark');$('#themeBtn').textContent=document.body.classList.contains('dark')?'☀':'☾';$('#themeBtn').onclick=()=>{document.body.classList.toggle('dark');const dark=document.body.classList.contains('dark');localStorage.setItem('numvero-theme',dark?'dark':'light');$('#themeBtn').textContent=dark?'☀':'☾'};
const params=new URLSearchParams(location.search);if(params.get('q')){$('#search').value=params.get('q');renderCards(params.get('q'));}else renderCards();