const $=s=>document.querySelector(s);const app=$('#app'),ws=$('#workspace');
$('#theme').onclick=()=>{document.body.classList.toggle('dark');$('#theme').textContent=document.body.classList.contains('dark')?'☀':'☾';localStorage.setItem('theme',document.body.classList.contains('dark')?'dark':'light')};if(localStorage.getItem('theme')==='dark'){$('body').classList.add('dark');$('#theme').textContent='☀'}
const field=(label,id,type='number',placeholder='')=>`<div class="field"><label for="${id}">${label}</label><input id="${id}" type="${type}" placeholder="${placeholder}" ${type==='number'?'inputmode="decimal"':''}></div>`;const btn=(text,id='go')=>`<button id="${id}" type="button">${text}</button>`;const panel=(title,body)=>`<div class="panel"><p class="eyebrow">NUMVERO TOOL</p><h2>${title}</h2>${body}</div>`;const val=id=>Number($('#'+id).value);
const tools={
basic:()=>panel('Basic Calculator',`<input id="display" class="display" style="width:100%;font-size:2rem;padding:18px;border:1px solid #cfd8d1;border-radius:12px;background:transparent;color:inherit" placeholder="0"><div class="actions">${['7','8','9','÷','4','5','6','×','1','2','3','−','0','.','+','%','(',')','⌫','C','='].map(x=>btn(x,'k'+x)).join('')}</div>`),
scientific:()=>panel('Scientific Calculator',`<input id="display" style="width:100%;font-size:1.7rem;padding:18px;border:1px solid #cfd8d1;border-radius:12px;background:transparent;color:inherit" placeholder="0"><div class="actions">${['sin','cos','tan','√','log','ln','π','e','x²','^','(',')','7','8','9','÷','4','5','6','×','1','2','3','−','0','.','+','C','='].map(x=>btn(x,'k'+x)).join('')}</div>`),
percentage:()=>panel('Percentage Calculator',`<div class="fields">${field('Percentage','p')} ${field('Number','n')}</div><div class="actions">${btn('Calculate','go')}</div><div id="result" class="result"></div>`),
age:()=>panel('Age Calculator',`<div class="fields">${field('Date of birth','dob','date')} ${field('Calculate age on','asof','date')}</div><div class="actions">${btn('Calculate','go')}</div><div id="result" class="result"></div>`),
simple:()=>panel('Simple Interest',`<div class="fields">${field('Principal','p')} ${field('Rate % per year','r')} ${field('Time in years','t')}</div><div class="actions">${btn('Calculate','go')}</div><div id="result" class="result"></div>`),
compound:()=>panel('Compound Interest',`<div class="fields">${field('Principal','p')} ${field('Rate % per year','r')} ${field('Years','t')} ${field('Compounds per year','n')}</div><div class="actions">${btn('Calculate','go')}</div><div id="result" class="result"></div>`),
emi:()=>panel('Loan EMI',`<div class="fields">${field('Loan amount','p')} ${field('Annual interest %','r')} ${field('Loan term in years','t')}</div><div class="actions">${btn('Calculate','go')}</div><div id="result" class="result"></div>`),
ratio:()=>panel('Ratio Simplifier & Splitter',`<div class="fields">${field('First number','a')} ${field('Second number','b')} ${field('Total to split','total')}</div><div class="actions">${btn('Calculate','go')}</div><div id="result" class="result"></div>`),
units:()=>panel('Unit Converter',`<div class="fields"><div class="field"><label>Type</label><select id="type"><option>Length</option><option>Weight</option><option>Temperature</option></select></div>${field('Value','v')}<div class="field"><label>From</label><select id="from"></select></div><div class="field"><label>To</label><select id="to"></select></div></div><div class="actions">${btn('Convert','go')}</div><div id="result" class="result"></div>`)};
function basicEngine(sci=false){let d=$('#display'),expr='';document.querySelectorAll('[id^=k]').forEach(b=>b.onclick=()=>{let x=b.textContent;if(x==='C'){expr=''}else if(x==='⌫'){expr=expr.slice(0,-1)}else if(x==='='){try{let e=expr.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('√','Math.sqrt').replaceAll('π','Math.PI').replaceAll('ln','Math.log').replaceAll('log','Math.log10').replaceAll('sin','Math.sin').replaceAll('cos','Math.cos').replaceAll('tan','Math.tan').replaceAll('^','**').replaceAll('x²','**2');if(!/^[0-9+\-*/().%*A-Za-z]+$/.test(e))throw 0;expr=String(Function('return '+e)());}catch{expr='Error'}}else{expr+=x}d.value=expr})}
function calc(name){const r=$('#result');try{if(name==='percentage')r.textContent=`${val('p')}% of ${val('n')} = ${(val('p')/100*val('n')).toFixed(4)}`;if(name==='simple'){let i=val('p')*val('r')*val('t')/100;r.textContent=`Interest: ${i.toFixed(2)}\nTotal: ${(val('p')+i).toFixed(2)}`};if(name==='compound'){let a=val('p')*Math.pow(1+val('r')/100/val('n'),val('n')*val('t'));r.textContent=`Interest: ${(a-val('p')).toFixed(2)}\nAmount: ${a.toFixed(2)}`};if(name==='emi'){let P=val('p'),m=val('r')/1200,N=val('t')*12;let e=m?P*m*Math.pow(1+m,N)/(Math.pow(1+m,N)-1):P/N;r.textContent=`Monthly EMI: ${e.toFixed(2)}\nTotal payment: ${(e*N).toFixed(2)}\nTotal interest: ${(e*N-P).toFixed(2)}`};if(name==='ratio'){let a=val('a'),b=val('b'),g=Math.abs(gcd(a,b));r.textContent=`Simplified ratio: ${a/g} : ${b/g}\nSplit: ${(val('total')*a/(a+b)).toFixed(2)} and ${(val('total')*b/(a+b)).toFixed(2)}`};if(name==='age'){let d=new Date($('#dob').value),e=new Date($('#asof').value);if(d>e)throw 0;let y=e.getFullYear()-d.getFullYear(),m=e.getMonth()-d.getMonth(),day=e.getDate()-d.getDate();if(day<0){m--;day+=new Date(e.getFullYear(),e.getMonth(),0).getDate()}if(m<0){y--;m+=12}r.textContent=`${y} years, ${m} months, ${day} days`;}}catch{r.textContent='Please enter valid values.'}}
function gcd(a,b){while(b){[a,b]=[b,a%b]}return a}
function units(){const sets={Length:['Meters','Kilometers','Centimeters','Miles','Feet'],Weight:['Kilograms','Grams','Pounds'],Temperature:['Celsius','Fahrenheit','Kelvin']};const t=$('#type'),f=$('#from'),to=$('#to');function fill(){f.innerHTML=to.innerHTML=sets[t.value].map(x=>`<option>${x}</option>`).join('')}t.onchange=fill;fill();$('#go').onclick=()=>{let x=val('v'),type=t.value,a=f.value,b=to.value;if(type==='Length'){let m={'Meters':1,'Kilometers':1000,'Centimeters':.01,'Miles':1609.344,'Feet':.3048};x=x*m[a]/m[b]}else if(type==='Weight'){let m={'Kilograms':1,'Grams':.001,'Pounds':.45359237};x=x*m[a]/m[b]}else{let c=a==='Celsius'?x:a==='Fahrenheit'?(x-32)*5/9:x-273.15;x=b==='Celsius'?c:b==='Fahrenheit'?c*9/5+32:c+273.15}$('#result').textContent=`${x}`}}
function open(name){app.innerHTML=tools[name]();ws.classList.add('active');location.hash='workspace';if(name==='basic'||name==='scientific')basicEngine(name==='scientific');if(name==='units')units();if(!['basic','scientific','units'].includes(name))$('#go').onclick=()=>calc(name)}
document.querySelectorAll('[data-open]').forEach(x=>x.onclick=()=>open(x.dataset.open));$('#back').onclick=()=>{ws.classList.remove('active');location.hash='calculators'};
