import { useEffect, useMemo, useState } from 'react';
import { ArrowRight, Calculator, Check, ChevronRight, Moon, Search, Sun, X } from 'lucide-react';

type Tool = { id:string; name:string; description:string; icon:string; keywords:string[] };
const tools:Tool[] = [
  {id:'basic',name:'Basic Calculator',description:'Fast everyday arithmetic with brackets, percentages and keyboard support.',icon:'+',keywords:['math','arithmetic','add','subtract','multiply','divide']},
  {id:'scientific',name:'Scientific Calculator',description:'Trigonometry, logarithms, powers, roots, constants and DEG/RAD modes.',icon:'√',keywords:['science','sin','cos','tan','log','root','power']},
  {id:'percentage',name:'Percentage Calculator',description:'Calculate percentages, percentage change, increases, discounts and tips.',icon:'%',keywords:['percent','discount','increase','decrease','tip']},
  {id:'age',name:'Age Calculator',description:'Find an exact age in years, months and days between two dates.',icon:'AGE',keywords:['date','birthday','dob']},
  {id:'simple',name:'Simple Interest',description:'Calculate simple interest and total amount from principal, rate and time.',icon:'SI',keywords:['interest','finance','money']},
  {id:'compound',name:'Compound Interest',description:'Estimate compound growth with flexible compounding periods.',icon:'CI',keywords:['interest','investment','growth','finance']},
  {id:'emi',name:'Loan EMI Calculator',description:'Estimate monthly EMI, total repayment and total interest.',icon:'₹',keywords:['loan','emi','finance','home loan']},
  {id:'ratio',name:'Ratio Calculator',description:'Simplify ratios and split a total proportionally.',icon:'∶',keywords:['ratio','proportion','math']},
  {id:'units',name:'Unit Converter',description:'Convert length, weight and temperature instantly.',icon:'↔',keywords:['convert','length','weight','temperature','units']}
];

const fmt=(n:number)=>Number.isFinite(n)?Number(n.toFixed(10)).toLocaleString('en-IN',{maximumFractionDigits:10}):'Error';
const num=(v:string)=>{const n=Number(v);return Number.isFinite(n)?n:null};
function evalMath(input:string,deg=true){
  const s=input.replaceAll('×','*').replaceAll('÷','/').replaceAll('−','-').replaceAll('√','sqrt').replaceAll('π','pi').replaceAll('%','/100');
  const tokens=s.match(/(?:asin|acos|atan|sin|cos|tan|sqrt|log|ln|pi|e|\d*\.?\d+|[+\-*/%^()])/g)||[]; let i=0;
  const primary=():number=>{const t=tokens[i++]; if(t===undefined)throw Error('Invalid'); if(/^\d|^\.\d/.test(t))return Number(t); if(t==='pi')return Math.PI;if(t==='e')return Math.E;if(t==='-')return-primary();if(t==='+')return primary();if(t==='('){const v=expr();if(tokens[i++]!==')')throw Error('Invalid');return v} if(['sin','cos','tan','asin','acos','atan','sqrt','log','ln'].includes(t)){if(tokens[i++]!=='(')throw Error('Invalid');const x=expr();if(tokens[i++]!==')')throw Error('Invalid');const r=deg?x*Math.PI/180:x;const inv=deg?180/Math.PI:1;return t==='sin'?Math.sin(r):t==='cos'?Math.cos(r):t==='tan'?Math.tan(r):t==='asin'?Math.asin(x)*inv:t==='acos'?Math.acos(x)*inv:t==='atan'?Math.atan(x)*inv:t==='sqrt'?Math.sqrt(x):t==='log'?Math.log10(x):Math.log(x)} throw Error('Invalid')};
  const power=():number=>{let a=primary();if(tokens[i]==='^'){i++;a=Math.pow(a,power())}return a};
  const term=():number=>{let a=power();while(['*','/'].includes(tokens[i])){const o=tokens[i++],b=power();a=o==='*'?a*b:a/b}return a};
  const expr=():number=>{let a=term();while(['+','-'].includes(tokens[i])){const o=tokens[i++],b=term();a=o==='+'?a+b:a-b}return a};
  const out=expr();if(i!==tokens.length||!Number.isFinite(out))throw Error('Invalid');return out;
}

function CalculatorPanel({id,onClose}:{id:string;onClose:()=>void}){
 const [result,setResult]=useState('Enter values and calculate.');
 const [display,setDisplay]=useState(''); const [deg,setDeg]=useState(true);
 const [v,setV]=useState<Record<string,string>>({});
 const set=(k:string,x:string)=>setV(p=>({...p,[k]:x}));
 const calculate=()=>{try{
   if(id==='basic'||id==='scientific'){setResult(fmt(evalMath(display,deg)));return}
   if(id==='percentage'){const p=num(v.p||''),n=num(v.n||'');if(p===null||n===null)throw Error();setResult(`${fmt(p)}% of ${fmt(n)} = ${fmt(p*n/100)}`);return}
   if(id==='age'){const d=new Date(v.dob+'T00:00:00'),e=new Date((v.asof||new Date().toISOString().slice(0,10))+'T00:00:00');if(!v.dob||d>e)throw Error();let y=e.getFullYear()-d.getFullYear(),m=e.getMonth()-d.getMonth(),day=e.getDate()-d.getDate();if(day<0){m--;day+=new Date(e.getFullYear(),e.getMonth(),0).getDate()}if(m<0){y--;m+=12}setResult(`${y} years, ${m} months, ${day} days`);return}
   const p=num(v.p||''),r=num(v.r||''),t=num(v.t||'');if(p===null||r===null||t===null)throw Error();
   if(id==='simple'){const i=p*r*t/100;setResult(`Interest: ${fmt(i)}\nTotal amount: ${fmt(p+i)}`)}
   if(id==='compound'){const n=num(v.n||'');if(n===null||n<=0)throw Error();const a=p*Math.pow(1+r/100/n,n*t);setResult(`Interest: ${fmt(a-p)}\nAmount: ${fmt(a)}`)}
   if(id==='emi'){if(t<=0)throw Error();const monthly=r/1200,N=t*12,e=monthly===0?p/N:p*monthly*Math.pow(1+monthly,N)/(Math.pow(1+monthly,N)-1);setResult(`Monthly EMI: ${fmt(e)}\nTotal payment: ${fmt(e*N)}\nTotal interest: ${fmt(e*N-p)}`)}
   if(id==='ratio'){const a=num(v.a||''),b=num(v.b||''),total=v.total?num(v.total):null;if(a===null||b===null||a<=0||b<=0)throw Error();const gcd=(x:number,y:number):number=>y?gcd(y,x%y):Math.abs(x);let text=`Simplified ratio: ${a/gcd(a,b)} : ${b/gcd(a,b)}`;if(total!==null)text+=`\nSplit: ${fmt(total*a/(a+b))} and ${fmt(total*b/(a+b))}`;setResult(text)}
 }catch{setResult('Please enter valid values.')}};
 const input=(label:string,key:string,type='number')=><label className="field"><span>{label}</span><input type={type} value={v[key]||''} onChange={e=>set(key,e.target.value)} /></label>;
 const key=(x:string)=>{if(x==='='){calculate();return}if(x==='C'){setDisplay('');return}if(x==='⌫'){setDisplay(display.slice(0,-1));return}setDisplay(display+x)};
 const keypad=['C','⌫','(',')','7','8','9','÷','4','5','6','×','1','2','3','−','0','.','%','+','='];
 return <div className="modal-wrap" role="dialog" aria-modal="true" aria-label={tools.find(t=>t.id===id)?.name} onMouseDown={e=>e.currentTarget===e.target&&onClose()}><div className="calculator-modal"><div className="modal-head"><div><p className="eyebrow">NUMVERO TOOL</p><h2>{tools.find(t=>t.id===id)?.name}</h2></div><button className="icon-button" onClick={onClose} aria-label="Close"><X/></button></div>
 {(id==='basic'||id==='scientific')?<><input className="calc-display" autoFocus value={display} onChange={e=>setDisplay(e.target.value)} onKeyDown={e=>{if(e.key==='Enter')calculate();if(e.key==='Escape')onClose()}} placeholder="0" aria-label="Calculator expression"/><div className="mode-row">{id==='scientific'&&<button onClick={()=>setDeg(!deg)}>{deg?'DEG':'RAD'}</button>}<button onClick={()=>setDisplay('')}>Clear</button></div>{id==='scientific'&&<div className="scientific-row">{['sin(','cos(','tan(','sqrt(','log(','ln(','π','e','^'].map(x=><button key={x} onClick={()=>setDisplay(display+x)}>{x}</button>)}</div>}<div className="keypad">{keypad.map(x=><button key={x} onClick={()=>key(x)} className={x==='='?'primary-key':''}>{x}</button>)}</div></>:<><div className="form-grid">{id==='percentage'&&<>{input('Percentage','p')}{input('Number','n')}</>}{id==='age'&&<>{input('Date of birth','dob','date')}{input('Calculate age on','asof','date')}</>}{id==='simple'&&<>{input('Principal','p')}{input('Rate % per year','r')}{input('Time in years','t')}</>}{id==='compound'&&<>{input('Principal','p')}{input('Rate % per year','r')}{input('Years','t')}{input('Compounds per year','n')}</>}{id==='emi'&&<>{input('Loan amount','p')}{input('Annual interest %','r')}{input('Loan term in years','t')}</>}{id==='ratio'&&<>{input('First value','a')}{input('Second value','b')}{input('Total to split (optional)','total')}</>}{id==='units'&&<UnitFields v={v} set={set}/>}</div><button className="calculate-button" onClick={calculate}>Calculate <ArrowRight/></button></>}
 <div className="result" role="status">{result}</div>{id==='emi'&&<p className="hint">Estimate only; actual lender terms may differ.</p>}</div></div>
}
function UnitFields({v,set}:{v:Record<string,string>;set:(k:string,x:string)=>void}){const cat=v.cat||'Length';const opts=cat==='Length'?['Meters','Kilometers','Centimeters','Millimeters','Miles','Feet','Inches']:cat==='Weight'?['Kilograms','Grams','Milligrams','Pounds','Ounces']:['Celsius','Fahrenheit','Kelvin'];return <><label className="field"><span>Category</span><select value={cat} onChange={e=>set('cat',e.target.value)}><option>Length</option><option>Weight</option><option>Temperature</option></select></label><label className="field"><span>Value</span><input value={v.value||''} onChange={e=>set('value',e.target.value)}/></label><label className="field"><span>From</span><select value={v.from||opts[0]} onChange={e=>set('from',e.target.value)}>{opts.map(o=><option key={o}>{o}</option>)}</select></label><label className="field"><span>To</span><select value={v.to||opts[1]} onChange={e=>set('to',e.target.value)}>{opts.map(o=><option key={o}>{o}</option>)}</select></label></>}

export function App(){
 const [dark,setDark]=useState(()=>localStorage.getItem('numvero-theme')==='dark'); const [query,setQuery]=useState(''); const [open,setOpen]=useState<string|null>(null); const path=window.location.pathname;
 useEffect(()=>{document.documentElement.classList.toggle('dark',dark);localStorage.setItem('numvero-theme',dark?'dark':'light');},[dark]);
 useEffect(()=>{document.title=path==='/about'?'About Numvero — Free Online Calculators':path==='/contact'?'Contact Numvero':'Numvero — Free Online Calculators';},[path]);
 const filtered=useMemo(()=>tools.filter(t=>(t.name+' '+t.description+' '+t.keywords.join(' ')).toLowerCase().includes(query.toLowerCase())),[query]);
 const go=(p:string)=>{window.history.pushState({},'',p);window.dispatchEvent(new PopStateEvent('popstate'))};
 const [tick,setTick]=useState(0);useEffect(()=>{const f=()=>setTick(x=>x+1);addEventListener('popstate',f);return()=>removeEventListener('popstate',f)},[]);void tick;
 return <><header className="nav"><a className="logo" href="/" onClick={e=>{e.preventDefault();go('/')}}><span className="logo-mark">N</span>Numvero</a><nav><a href="/" onClick={e=>{e.preventDefault();go('/')}}>Home</a><a href="#calculators">Calculators</a><a href="/about" onClick={e=>{e.preventDefault();go('/about')}}>About</a><a href="/contact" onClick={e=>{e.preventDefault();go('/contact')}}>Contact</a></nav><div className="nav-actions"><button className="theme-toggle" onClick={()=>setDark(!dark)} aria-label="Toggle dark mode">{dark?<Sun/>:<Moon/>}</button></div></header>
 {path==='/about'?<About go={go}/>:path==='/contact'?<Contact/>:<main><section className="hero"><div className="hero-copy"><span className="badge">FREE • FAST • PRIVATE</span><h1>Numbers, <span>simplified.</span></h1><p>Clean, reliable calculators for school, work, money and everyday life. No ads. No login. Just calculate.</p><div className="hero-actions"><a className="button primary" href="#calculators">Explore calculators <ArrowRight/></a><button className="button secondary" onClick={()=>setOpen(tools[Math.floor(Math.random()*tools.length)].id)}>Try a random tool</button></div><div className="trust"><span><Check/>No sign-up</span><span><Check/>No ads</span><span><Check/>Runs in your browser</span></div></div><div className="hero-orb"><div className="orb-grid"></div><strong>123</strong><span>NUMVERO</span><i>+</i><i>×</i><i>%</i></div></section>
 <section id="calculators" className="section"><div className="section-top"><div><span className="eyebrow">THE TOOLKIT</span><h2>Everything you need to calculate.</h2><p>Pick a tool and get a clear answer without the clutter.</p></div><div className="search-box"><Search/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search calculators..." aria-label="Search calculators"/>{query&&<button onClick={()=>setQuery('')} aria-label="Clear search"><X/></button>}</div></div><div className="tool-grid">{filtered.map((t,i)=><button className="tool-card" key={t.id} onClick={()=>setOpen(t.id)}><div className="tool-number">{String(i+1).padStart(2,'0')}</div><div className="tool-icon">{t.icon}</div><h3>{t.name}</h3><p>{t.description}</p><span className="tool-link">Open calculator <ChevronRight/></span></button>)}</div>{filtered.length===0&&<div className="empty">No calculator matches “{query}”.</div>}</section>
 <section className="feature-section"><div><span className="eyebrow">WHY NUMVERO</span><h2>Built around the way people actually calculate.</h2></div><div className="features"><article><b>01</b><h3>Clear by default</h3><p>Focused screens, readable results and no unnecessary distractions.</p></article><article><b>02</b><h3>Private by design</h3><p>Normal calculations stay in your browser. No account is needed.</p></article><article><b>03</b><h3>Works everywhere</h3><p>Responsive controls, keyboard support and touch-friendly layouts.</p></article></div></section>
 <section className="cta-section"><span className="eyebrow">READY?</span><h2>Stop searching. Start calculating.</h2><p>One clean place for the everyday numbers you need.</p><a className="button primary" href="#calculators">Browse all calculators <ArrowRight/></a></section></main>}
 <footer><div><a className="logo" href="/" onClick={e=>{e.preventDefault();go('/')}}><span className="logo-mark">N</span>Numvero</a><p>Free calculators. No ads. No login.</p></div><div className="footer-links"><a href="/about" onClick={e=>{e.preventDefault();go('/about')}}>About</a><a href="/contact" onClick={e=>{e.preventDefault();go('/contact')}}>Contact</a></div><small>© {new Date().getFullYear()} Numvero</small></footer>{open&&<CalculatorPanel id={open} onClose={()=>setOpen(null)}/>}</>;
}
function About({go}:{go:(p:string)=>void}){return <main className="simple-page"><span className="badge">ABOUT NUMVERO</span><h1>Useful math without the noise.</h1><p className="lead">Numvero is a focused calculator hub built for quick answers. The idea is simple: make common calculations easier to find, easier to understand and easier to use.</p><div className="about-cards"><article><h2>Our promise</h2><p>No ads. No account wall. No unnecessary steps. Numvero is designed to get you from a question to an answer quickly.</p></article><article><h2>Built for everyone</h2><p>Students, families, professionals and anyone who needs a dependable calculation can use the same clean toolkit.</p></article></div><a className="button primary" href="/" onClick={e=>{e.preventDefault();go('/')}}>Explore calculators <ArrowRight/></a></main>}
function Contact(){return <main className="simple-page"><span className="badge">CONTACT</span><h1>Have feedback?</h1><p className="lead">Numvero is built to improve. For feedback, bug reports or calculator suggestions, use the project repository or contact the site owner through the published project channels.</p><div className="contact-box"><h2>Help make Numvero better</h2><p>Tell us which calculator is missing, what feels confusing, or what should be improved. Short, specific feedback is the most useful.</p><a className="button primary" href="https://github.com/bankarshashank47-cloud/Numvero" target="_blank" rel="noreferrer">Open project on GitHub <ArrowRight/></a></div></main>}
